import { useState, useEffect, useRef } from 'react';
import { useParams, useNavigate, useLoaderData } from 'react-router';
import { FaEdit, FaRedo, FaTrash } from 'react-icons/fa';
import RecipeView from '../components/RecipeView';
import RecipeSkeleton from '../components/RecipeSkeleton';
import api from '../utils/api';
import { computeRecipeDiffAsHtml } from '../utils/diffHelper';
import { useAuth } from '../components/AuthProvider';
import { useLayoutContext } from '../components/Layout';
import '../styles/RecipeDetail.css';

export async function loader({ params }) {
  const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:5001';
  try {
    const response = await fetch(`${apiUrl}/api/recipe/${params.id}`);
    if (!response.ok) {
      return { recipe: null, error: "Failed to fetch" };
    }
    const data = await response.json();
    return data;
  } catch (e) {
    return { recipe: null, error: e.message };
  }
}

export function meta({ data }) {
  if (!data || !data.recipe) {
    return [
      { title: "RecipeLab" }
    ];
  }
  
  const title = (data.recipe && data.recipe.title) ? data.recipe.title : "Recipe";
  const desc = data.prompt || (data.recipe ? `A delicious ${data.recipe.complexity || ''} ${data.recipe.diet || ''} recipe generated by AI.` : "Generate delicious recipes instantly with AI.");
  const image = data.image_url || "/og-image.png";
  
  return [
    { title: `RecipeLab - ${title}` },
    { property: "og:title", content: `RecipeLab - ${title}` },
    { property: "og:description", content: desc },
    { property: "og:image", content: image },
    { property: "og:url", content: `https://recipelab.app/recipe/${data.id || ''}` },
    { name: "twitter:card", content: "summary_large_image" },
    { name: "twitter:title", content: `RecipeLab - ${title}` },
    { name: "twitter:description", content: desc },
    { name: "twitter:image", content: image },
  ];
}

function RecipeDetail() {
  const loaderData = useLoaderData();
  const user = useAuth();
  const { 
    favoriteIds = [], 
    toggleFavorite, 
    isMobile, 
    sidebarCollapsed, 
    onToggleSidebar, 
    wakeLockEnabled, 
    onToggleWakeLock 
  } = useLayoutContext() || {};
  const recipeRef = useRef(null);
  const { id } = useParams();
  const navigate = useNavigate();
  const [recipe, setRecipe] = useState(loaderData?.recipe || null);
  const [prevRecipe, setPrevRecipe] = useState(loaderData?.recipe || null);
  const [recipeUID, setRecipeUID] = useState(loaderData?.uid || '');
  const [prompt, setPrompt] = useState(loaderData?.prompt || '');
  const [timestamp, setTimestamp] = useState(loaderData?.timestamp || '');
  const [displayName, setDisplayName] = useState(loaderData?.displayName || '');
  const [imageUrl, setImageUrl] = useState(loaderData?.image_url || '');
  const [error, setError] = useState(loaderData?.error || '');
  const [loading, setLoading] = useState(loaderData?.recipe ? false : true);
  const [modification, setModification] = useState('');
  const [updateLoading, setUpdateLoading] = useState(false);
  const [regenerateLoading, setRegenerateLoading] = useState(false);

  const fetchRecipe = async () => {
    try {
      const response = await api.get(`/api/recipe/${id}`);
      if (response.status !== 200) throw new Error('Network response was not ok');
      const data = response.data;
      setRecipe(data.recipe);
      setPrevRecipe(data.recipe);
      setTimestamp(data.timestamp);
      setRecipeUID(data.uid);
      setDisplayName(data.displayName);
      setImageUrl(data.image_url || '');
      setPrompt(data.prompt || '');
    } catch (err) {
      console.error('Error fetching recipe:', err);
      setError('There was an error fetching the recipe.');
    }
    setLoading(false);
  };

  useEffect(() => {
    if (loaderData?.recipe) {
      setRecipe(loaderData.recipe);
      setPrevRecipe(loaderData.recipe);
      setRecipeUID(loaderData.uid);
      setDisplayName(loaderData.displayName);
      setTimestamp(loaderData.timestamp);
      setImageUrl(loaderData.image_url);
      setPrompt(loaderData.prompt || '');
      setLoading(false);
    }
  }, [loaderData]);

  useEffect(() => {
    if (!loaderData?.recipe) {
      setLoading(true);
      setImageUrl('');
    }
    fetchRecipe();
    requestAnimationFrame(() => {
      window.scrollTo(0, 0);
    });
  }, [id]);

  const handleDelete = async () => {
    const confirmed = window.confirm("Are you sure you want to delete this recipe? This action cannot be undone.");
    if (!confirmed) return;
    
    try {
      const response = await api.patch(`/api/recipe/${id}/archive`);
      if (response.status !== 200) throw new Error('Failed to archive recipe');
      navigate('/');
    } catch (err) {
      console.error('Error deleting recipe:', err);
      setError('There was an error deleting the recipe.');
    }
  };

  const handleUpdateRecipe = async () => {
    if (!modification) return;
    setUpdateLoading(true);
    try {
      setPrevRecipe(recipe);
      const response = await api.post('/api/update-recipe', {
        id,
        original_recipe: recipe,
        modifications: modification,
      });
      if (response.status !== 200) throw new Error('Update failed');
      setRecipe(response.data.recipe);
      setModification('');

      // Scroll the recipe element into view after updating.
      if (recipeRef.current) {
        recipeRef.current.scrollIntoView({ behavior: 'smooth' });
      }
    } catch (err) {
      console.error('Error updating recipe:', err);
      setError('There was an error updating the recipe.');
    }
    setUpdateLoading(false);
  };

  const handleRegenerate = async () => {
    if (!prompt) return;
    setRegenerateLoading(true);
    setError('');
    try {
      const response = await api.post('/api/generate-recipe', { prompt });
      if (response.status !== 200) throw new Error('Network response was not ok');
      const data = response.data;
      // Navigate to the new recipe
      navigate(`/recipe/${data.id}`);
    } catch (err) {
      console.error('Error regenerating recipe:', err);
      setError('There was an error regenerating the recipe.');
    }
    setRegenerateLoading(false);
  };

  // Compute the diff HTML for inline highlighting.
  const diffRecipe = prevRecipe !== recipe
    ? computeRecipeDiffAsHtml(prevRecipe, recipe)
    : recipe;

  return (
    <div className="recipe-detail-page">
      {loading ? (
        <RecipeSkeleton
          isMobile={isMobile}
          sidebarCollapsed={sidebarCollapsed}
          onToggleSidebar={onToggleSidebar}
          showImageSkeleton={import.meta.env.VITE_ENABLE_IMAGE_GENERATION === 'true'}
        />
      ) : error ? (
        <p className="error">{error}</p>
      ) : (
        <div className="recipe" ref={recipeRef}>
          <RecipeView
            recipe={diffRecipe}
            author={displayName}
            timestamp={timestamp}
            isFavorite={favoriteIds.includes(id)}
            onToggleFavorite={toggleFavorite}
            recipeId={id}
            isMobile={isMobile}
            sidebarCollapsed={sidebarCollapsed}
            onToggleSidebar={onToggleSidebar}
            wakeLockEnabled={wakeLockEnabled}
            onToggleWakeLock={onToggleWakeLock}
            imageUrl={imageUrl}
            shareUrl={`${window.location.origin}/recipe/${id}`}
          />
          {user && recipeUID === user.uid && (
            <div className="recipe-management-section">
              <div className="update-section">
                <input
                  type="text"
                  className="modification-input"
                  placeholder="Enter modifications (e.g., remove onions)"
                  value={modification}
                  onChange={(e) => setModification(e.target.value)}
                />
                <div className="management-actions">
                  <div className="modification-buttons">
                    <button type="submit" onClick={handleUpdateRecipe} disabled={updateLoading || regenerateLoading || !modification}>
                      <FaEdit className="btn-icon" />
                      {updateLoading ? 'Updating...' : 'Update Recipe'}
                    </button>
                    {prompt && (
                      <button type="button" onClick={handleRegenerate} disabled={updateLoading || regenerateLoading} className="regenerate-btn">
                        <FaRedo className="btn-icon" />
                        {regenerateLoading ? 'Regenerating...' : 'Regenerate'}
                      </button>
                    )}
                  </div>
                  <button onClick={handleDelete} className="delete-btn">
                    <FaTrash className="btn-icon" />
                    Delete Recipe
                  </button>
                </div>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export default RecipeDetail;
