// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/recipe/:id": {
    params: {
      "id": string;
    };
  };
  "/preferences": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/recipe/:id" | "/preferences" | "/login" | "/signup" | "/*";
  };
  "routes/layout_app.jsx": {
    id: "routes/layout_app";
    page: "/" | "/recipe/:id" | "/preferences";
  };
  "pages/Home.jsx": {
    id: "pages/Home";
    page: "/";
  };
  "pages/RecipeDetail.jsx": {
    id: "pages/RecipeDetail";
    page: "/recipe/:id";
  };
  "pages/Preferences.jsx": {
    id: "pages/Preferences";
    page: "/preferences";
  };
  "pages/Login.jsx": {
    id: "pages/Login";
    page: "/login";
  };
  "pages/SignUp.jsx": {
    id: "pages/SignUp";
    page: "/signup";
  };
  "pages/NotFound.jsx": {
    id: "pages/NotFound";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/layout_app": typeof import("./app/routes/layout_app.jsx");
  "pages/Home": typeof import("./app/pages/Home.jsx");
  "pages/RecipeDetail": typeof import("./app/pages/RecipeDetail.jsx");
  "pages/Preferences": typeof import("./app/pages/Preferences.jsx");
  "pages/Login": typeof import("./app/pages/Login.jsx");
  "pages/SignUp": typeof import("./app/pages/SignUp.jsx");
  "pages/NotFound": typeof import("./app/pages/NotFound.jsx");
};